/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatchxr-astronaut-81338170583f4e4cab5e1731a6f9765a
Title: HatchXR Astronaut
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Astronaut({ animation, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/astronaut.glb')
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animation) {
      actions[animation]?.reset().fadeIn(0.24).play();
      return () => actions[animation]?.fadeOut(0.24);
    }
  }, [animation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={69.718}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Astronaut_matmat}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Matmat}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <group name="Object_6" />
                  <group
                    name="CINEMA_4D_Editor"
                    position={[5.713, 5.07, 4.713]}
                    rotation={[-Math.PI, 0.752, 2.865]}>
                    <group name="Object_79" />
                  </group>
                  <group name="Astronaut_mesh" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('//models/astronaut.glb')


/*
Animations:
- static
- jumpUp
- jumpDown
- moonwalk
- strafeLeft
- strafeRight
- float
- run
- silly



*/

